

server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  minio:
    bucket: abc
    access-key: minioadmin
    secret-key: minioadmin
    url: http://10.40.3.24:9000

springdoc:
  swagger-ui:
    operations-sorter: method